# Generated by Django 5.1.7 on 2025-03-31 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("txid", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=36)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["txid"], name="transaction_txid_482944_idx"),
                    models.Index(
                        fields=["wallet"], name="transaction_wallet__c63ebe_idx"
                    ),
                ],
            },
        ),
    ]
