# Generated by Django 4.2.20 on 2025-03-31 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'wallets',
                'ordering': ['label'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['label'], name='wallets_label_idx'),
        ),
    ]
